#!/bin/bash
# SPDX-FileCopyrightText: 2025 Mews Labs (https://www.mews-labs.com)
# SPDX-FileCopyrightText: 2025 RTE (https://www.rte-france.com)
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0

set -euo pipefail
# set -x

DEF_NAME=mewslabs-thermohl-uv
# PYTHON_VERSION="--python-preference=system"
PYTHON_VERSION="--python 3.12"

# -----------------------------------------------------------------------------

# -- dir for all envs
ENV_DIR=${ENV_DIR:-$HOME/ENV}
mkdir -p $ENV_DIR

# -- check uv install, update if necessary
if ! command -v uv &> /dev/null; then
    echo "uv not found; installing ..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    source $HOME/.cargo/env
else
    uv self update
    echo "uv already installed ($(uv --version))"
fi

# -- current env with link
VENV=${ENV_DIR}/${DEF_NAME}
VLNK=.uvenv
ln -sf $VENV $VLNK
uv venv --clear $VENV ${PYTHON_VERSION}
source $VENV/bin/activate

# -- upgrade pip
uv pip install --upgrade pip

## -- install local package
rm -rf build
uv sync --active --group dev

# -- end text
echo "---"
echo -e "\e[1mto start the environment, type :\e[0m"
echo "source ${VENV}/bin/activate"
echo ""
echo -e "\e[1mto stop the environment, type :\e[0m"
echo "deactivate"
